// Optimized Swiss postal code database with key cities
export interface PostalCodeData {
  postalCode: string;
  city: string;
  cantonCode: string;
}

export const swissPostalCodes: PostalCodeData[] = [
  // Basel-Landschaft (BL) - Including Allschwil
  { postalCode: '4123', city: 'Allschwil', cantonCode: 'BL' },
  { postalCode: '4101', city: 'Bruderholz', cantonCode: 'BL' },
  { postalCode: '4102', city: 'Binningen', cantonCode: 'BL' },
  { postalCode: '4103', city: 'Bottmingen', cantonCode: 'BL' },
  { postalCode: '4104', city: 'Oberwil', cantonCode: 'BL' },
  { postalCode: '4105', city: 'Biel-Benken', cantonCode: 'BL' },
  { postalCode: '4106', city: 'Therwil', cantonCode: 'BL' },
  { postalCode: '4107', city: 'Ettingen', cantonCode: 'BL' },
  { postalCode: '4108', city: 'Witterswil', cantonCode: 'BL' },
  { postalCode: '4109', city: 'Hofstetten-Flüh', cantonCode: 'BL' },
  { postalCode: '4110', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4111', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4112', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4113', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4114', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4115', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4116', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4117', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4118', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4119', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4120', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4121', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4122', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4124', city: 'Schönenbuch', cantonCode: 'BL' },
  { postalCode: '4125', city: 'Riehen', cantonCode: 'BS' },
  { postalCode: '4126', city: 'Bettingen', cantonCode: 'BS' },
  { postalCode: '4127', city: 'Birsfelden', cantonCode: 'BL' },
  { postalCode: '4128', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4129', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4130', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4131', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4132', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4133', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4134', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4135', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4136', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4137', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4138', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4139', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4140', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4141', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4142', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4143', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4144', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4145', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4146', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4147', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4148', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4149', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4150', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4151', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4152', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4153', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4154', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4155', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4156', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4157', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4158', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4159', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4160', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4161', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4162', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4163', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4164', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4165', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4166', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4167', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4168', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4169', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4170', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4171', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4172', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4173', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4174', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4175', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4176', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4177', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4178', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4179', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4180', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4181', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4182', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4183', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4184', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4185', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4186', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4187', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4188', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4189', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4190', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4191', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4192', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4193', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4194', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4195', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4196', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4197', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4198', city: 'Muttenz', cantonCode: 'BL' },
  { postalCode: '4199', city: 'Muttenz', cantonCode: 'BL' },
  
  // Basel-Stadt (BS)
  { postalCode: '4001', city: 'Basel', cantonCode: 'BS' },
  { postalCode: '4002', city: 'Basel', cantonCode: 'BS' },
  { postalCode: '4003', city: 'Basel', cantonCode: 'BS' },
  { postalCode: '4004', city: 'Basel', cantonCode: 'BS' },
  { postalCode: '4005', city: 'Basel', cantonCode: 'BS' },
  { postalCode: '4006', city: 'Basel', cantonCode: 'BS' },
  { postalCode: '4007', city: 'Basel', cantonCode: 'BS' },
  { postalCode: '4008', city: 'Basel', cantonCode: 'BS' },
  { postalCode: '4009', city: 'Basel', cantonCode: 'BS' },
  
  // Zürich (ZH)
  { postalCode: '8001', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8002', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8003', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8004', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8005', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8006', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8008', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8032', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8044', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8050', city: 'Zürich', cantonCode: 'ZH' },
  { postalCode: '8400', city: 'Winterthur', cantonCode: 'ZH' },
  { postalCode: '8401', city: 'Winterthur', cantonCode: 'ZH' },
  { postalCode: '8402', city: 'Winterthur', cantonCode: 'ZH' },
  { postalCode: '8403', city: 'Winterthur', cantonCode: 'ZH' },
  { postalCode: '8404', city: 'Winterthur', cantonCode: 'ZH' },
  
  // Bern (BE)
  { postalCode: '3000', city: 'Bern', cantonCode: 'BE' },
  { postalCode: '3001', city: 'Bern', cantonCode: 'BE' },
  { postalCode: '3002', city: 'Bern', cantonCode: 'BE' },
  { postalCode: '3003', city: 'Bern', cantonCode: 'BE' },
  { postalCode: '3004', city: 'Bern', cantonCode: 'BE' },
  { postalCode: '3005', city: 'Bern', cantonCode: 'BE' },
  { postalCode: '3006', city: 'Bern', cantonCode: 'BE' },
  { postalCode: '3007', city: 'Bern', cantonCode: 'BE' },
  { postalCode: '3008', city: 'Bern', cantonCode: 'BE' },
  { postalCode: '2500', city: 'Biel', cantonCode: 'BE' },
  { postalCode: '2501', city: 'Biel', cantonCode: 'BE' },
  { postalCode: '2502', city: 'Biel', cantonCode: 'BE' },
  { postalCode: '2503', city: 'Biel', cantonCode: 'BE' },
  { postalCode: '2504', city: 'Biel', cantonCode: 'BE' },
  { postalCode: '3600', city: 'Thun', cantonCode: 'BE' },
  { postalCode: '3601', city: 'Thun', cantonCode: 'BE' },
  { postalCode: '3602', city: 'Thun', cantonCode: 'BE' },
  { postalCode: '3603', city: 'Thun', cantonCode: 'BE' },
  { postalCode: '3604', city: 'Thun', cantonCode: 'BE' },
  { postalCode: '3605', city: 'Thun', cantonCode: 'BE' },
  
  // Geneva (GE)
  { postalCode: '1200', city: 'Genève', cantonCode: 'GE' },
  { postalCode: '1201', city: 'Genève', cantonCode: 'GE' },
  { postalCode: '1202', city: 'Genève', cantonCode: 'GE' },
  { postalCode: '1203', city: 'Genève', cantonCode: 'GE' },
  { postalCode: '1204', city: 'Genève', cantonCode: 'GE' },
  { postalCode: '1205', city: 'Genève', cantonCode: 'GE' },
  { postalCode: '1206', city: 'Genève', cantonCode: 'GE' },
  { postalCode: '1207', city: 'Genève', cantonCode: 'GE' },
  { postalCode: '1208', city: 'Genève', cantonCode: 'GE' },
  { postalCode: '1209', city: 'Genève', cantonCode: 'GE' },
  
  // Lausanne (VD)
  { postalCode: '1000', city: 'Lausanne', cantonCode: 'VD' },
  { postalCode: '1001', city: 'Lausanne', cantonCode: 'VD' },
  { postalCode: '1002', city: 'Lausanne', cantonCode: 'VD' },
  { postalCode: '1003', city: 'Lausanne', cantonCode: 'VD' },
  { postalCode: '1004', city: 'Lausanne', cantonCode: 'VD' },
  { postalCode: '1005', city: 'Lausanne', cantonCode: 'VD' },
  { postalCode: '1006', city: 'Lausanne', cantonCode: 'VD' },
  { postalCode: '1007', city: 'Lausanne', cantonCode: 'VD' },
  { postalCode: '1008', city: 'Lausanne', cantonCode: 'VD' },
  
  // St. Gallen (SG)
  { postalCode: '9000', city: 'St. Gallen', cantonCode: 'SG' },
  { postalCode: '9001', city: 'St. Gallen', cantonCode: 'SG' },
  { postalCode: '9002', city: 'St. Gallen', cantonCode: 'SG' },
  { postalCode: '9003', city: 'St. Gallen', cantonCode: 'SG' },
  { postalCode: '9004', city: 'St. Gallen', cantonCode: 'SG' },
  { postalCode: '9005', city: 'St. Gallen', cantonCode: 'SG' },
  { postalCode: '9006', city: 'St. Gallen', cantonCode: 'SG' },
  { postalCode: '9007', city: 'St. Gallen', cantonCode: 'SG' },
  { postalCode: '9008', city: 'St. Gallen', cantonCode: 'SG' },
  
  // Lucerne (LU)
  { postalCode: '6000', city: 'Luzern', cantonCode: 'LU' },
  { postalCode: '6001', city: 'Luzern', cantonCode: 'LU' },
  { postalCode: '6002', city: 'Luzern', cantonCode: 'LU' },
  { postalCode: '6003', city: 'Luzern', cantonCode: 'LU' },
  { postalCode: '6004', city: 'Luzern', cantonCode: 'LU' },
  { postalCode: '6005', city: 'Luzern', cantonCode: 'LU' },
  { postalCode: '6006', city: 'Luzern', cantonCode: 'LU' },
  { postalCode: '6007', city: 'Luzern', cantonCode: 'LU' },
  { postalCode: '6008', city: 'Luzern', cantonCode: 'LU' },
  
  // Lugano (TI)
  { postalCode: '6900', city: 'Lugano', cantonCode: 'TI' },
  { postalCode: '6901', city: 'Lugano', cantonCode: 'TI' },
  { postalCode: '6902', city: 'Lugano', cantonCode: 'TI' },
  { postalCode: '6903', city: 'Lugano', cantonCode: 'TI' },
  { postalCode: '6904', city: 'Lugano', cantonCode: 'TI' },
  { postalCode: '6905', city: 'Lugano', cantonCode: 'TI' },
  { postalCode: '6906', city: 'Lugano', cantonCode: 'TI' },
  { postalCode: '6907', city: 'Lugano', cantonCode: 'TI' },
  { postalCode: '6908', city: 'Lugano', cantonCode: 'TI' },
  { postalCode: '6500', city: 'Bellinzona', cantonCode: 'TI' },
  { postalCode: '6501', city: 'Bellinzona', cantonCode: 'TI' },
  { postalCode: '6502', city: 'Bellinzona', cantonCode: 'TI' },
  { postalCode: '6503', city: 'Bellinzona', cantonCode: 'TI' },
  { postalCode: '6504', city: 'Bellinzona', cantonCode: 'TI' },
  { postalCode: '6505', city: 'Bellinzona', cantonCode: 'TI' },
  
  // Aarau (AG)
  { postalCode: '5000', city: 'Aarau', cantonCode: 'AG' },
  { postalCode: '5001', city: 'Aarau', cantonCode: 'AG' },
  { postalCode: '5002', city: 'Aarau', cantonCode: 'AG' },
  { postalCode: '5003', city: 'Aarau', cantonCode: 'AG' },
  { postalCode: '5004', city: 'Aarau', cantonCode: 'AG' },
  
  // Chur (GR)
  { postalCode: '7000', city: 'Chur', cantonCode: 'GR' },
  { postalCode: '7001', city: 'Chur', cantonCode: 'GR' },
  { postalCode: '7002', city: 'Chur', cantonCode: 'GR' },
  { postalCode: '7003', city: 'Chur', cantonCode: 'GR' },
  { postalCode: '7004', city: 'Chur', cantonCode: 'GR' },
  
  // Additional major cities
  { postalCode: '8200', city: 'Schaffhausen', cantonCode: 'SH' },
  { postalCode: '8201', city: 'Schaffhausen', cantonCode: 'SH' },
  { postalCode: '8202', city: 'Schaffhausen', cantonCode: 'SH' },
  { postalCode: '8203', city: 'Schaffhausen', cantonCode: 'SH' },
  { postalCode: '8204', city: 'Schaffhausen', cantonCode: 'SH' },
  { postalCode: '8205', city: 'Schaffhausen', cantonCode: 'SH' },
  { postalCode: '4500', city: 'Solothurn', cantonCode: 'SO' },
  { postalCode: '4501', city: 'Solothurn', cantonCode: 'SO' },
  { postalCode: '4502', city: 'Solothurn', cantonCode: 'SO' },
  { postalCode: '4503', city: 'Solothurn', cantonCode: 'SO' },
  { postalCode: '4504', city: 'Solothurn', cantonCode: 'SO' },
  { postalCode: '4505', city: 'Solothurn', cantonCode: 'SO' },
  { postalCode: '2000', city: 'Neuchâtel', cantonCode: 'NE' },
  { postalCode: '2001', city: 'Neuchâtel', cantonCode: 'NE' },
  { postalCode: '2002', city: 'Neuchâtel', cantonCode: 'NE' },
  { postalCode: '2003', city: 'Neuchâtel', cantonCode: 'NE' },
  { postalCode: '2004', city: 'Neuchâtel', cantonCode: 'NE' },
  { postalCode: '2005', city: 'Neuchâtel', cantonCode: 'NE' },
  { postalCode: '1700', city: 'Fribourg', cantonCode: 'FR' },
  { postalCode: '1701', city: 'Fribourg', cantonCode: 'FR' },
  { postalCode: '1702', city: 'Fribourg', cantonCode: 'FR' },
  { postalCode: '1703', city: 'Fribourg', cantonCode: 'FR' },
  { postalCode: '1704', city: 'Fribourg', cantonCode: 'FR' },
  { postalCode: '1705', city: 'Fribourg', cantonCode: 'FR' },
  { postalCode: '1950', city: 'Sion', cantonCode: 'VS' },
  { postalCode: '1951', city: 'Sion', cantonCode: 'VS' },
  { postalCode: '1952', city: 'Sion', cantonCode: 'VS' },
  { postalCode: '1953', city: 'Sion', cantonCode: 'VS' },
  { postalCode: '1954', city: 'Sion', cantonCode: 'VS' },
  { postalCode: '1955', city: 'Sion', cantonCode: 'VS' },
  { postalCode: '9050', city: 'Appenzell', cantonCode: 'AI' },
  { postalCode: '9051', city: 'Appenzell', cantonCode: 'AI' },
  { postalCode: '9052', city: 'Appenzell', cantonCode: 'AI' },
  { postalCode: '9053', city: 'Appenzell', cantonCode: 'AI' },
  { postalCode: '9054', city: 'Appenzell', cantonCode: 'AI' },
  { postalCode: '9055', city: 'Appenzell', cantonCode: 'AI' },
  { postalCode: '9100', city: 'Herisau', cantonCode: 'AR' },
  { postalCode: '9101', city: 'Herisau', cantonCode: 'AR' },
  { postalCode: '9102', city: 'Herisau', cantonCode: 'AR' },
  { postalCode: '9103', city: 'Herisau', cantonCode: 'AR' },
  { postalCode: '9104', city: 'Herisau', cantonCode: 'AR' },
  { postalCode: '9105', city: 'Herisau', cantonCode: 'AR' },
  { postalCode: '8500', city: 'Frauenfeld', cantonCode: 'TG' },
  { postalCode: '8501', city: 'Frauenfeld', cantonCode: 'TG' },
  { postalCode: '8502', city: 'Frauenfeld', cantonCode: 'TG' },
  { postalCode: '8503', city: 'Frauenfeld', cantonCode: 'TG' },
  { postalCode: '8504', city: 'Frauenfeld', cantonCode: 'TG' },
  { postalCode: '8505', city: 'Frauenfeld', cantonCode: 'TG' },
  { postalCode: '4410', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4411', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4412', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4413', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4414', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '4415', city: 'Liestal', cantonCode: 'BL' },
  { postalCode: '6300', city: 'Zug', cantonCode: 'ZG' },
  { postalCode: '6301', city: 'Zug', cantonCode: 'ZG' },
  { postalCode: '6302', city: 'Zug', cantonCode: 'ZG' },
  { postalCode: '6303', city: 'Zug', cantonCode: 'ZG' },
  { postalCode: '6304', city: 'Zug', cantonCode: 'ZG' },
  { postalCode: '6305', city: 'Zug', cantonCode: 'ZG' },
  { postalCode: '6430', city: 'Schwyz', cantonCode: 'SZ' },
  { postalCode: '6431', city: 'Schwyz', cantonCode: 'SZ' },
  { postalCode: '6432', city: 'Schwyz', cantonCode: 'SZ' },
  { postalCode: '6433', city: 'Schwyz', cantonCode: 'SZ' },
  { postalCode: '6434', city: 'Schwyz', cantonCode: 'SZ' },
  { postalCode: '6435', city: 'Schwyz', cantonCode: 'SZ' },
  { postalCode: '6460', city: 'Altdorf', cantonCode: 'UR' },
  { postalCode: '6461', city: 'Altdorf', cantonCode: 'UR' },
  { postalCode: '6462', city: 'Altdorf', cantonCode: 'UR' },
  { postalCode: '6463', city: 'Altdorf', cantonCode: 'UR' },
  { postalCode: '6464', city: 'Altdorf', cantonCode: 'UR' },
  { postalCode: '6465', city: 'Altdorf', cantonCode: 'UR' },
  { postalCode: '6060', city: 'Sarnen', cantonCode: 'OW' },
  { postalCode: '6061', city: 'Sarnen', cantonCode: 'OW' },
  { postalCode: '6062', city: 'Sarnen', cantonCode: 'OW' },
  { postalCode: '6063', city: 'Sarnen', cantonCode: 'OW' },
  { postalCode: '6064', city: 'Sarnen', cantonCode: 'OW' },
  { postalCode: '6065', city: 'Sarnen', cantonCode: 'OW' },
  { postalCode: '6370', city: 'Stans', cantonCode: 'NW' },
  { postalCode: '6371', city: 'Stans', cantonCode: 'NW' },
  { postalCode: '6372', city: 'Stans', cantonCode: 'NW' },
  { postalCode: '6373', city: 'Stans', cantonCode: 'NW' },
  { postalCode: '6374', city: 'Stans', cantonCode: 'NW' },
  { postalCode: '6375', city: 'Stans', cantonCode: 'NW' },
  { postalCode: '8750', city: 'Glarus', cantonCode: 'GL' },
  { postalCode: '8751', city: 'Glarus', cantonCode: 'GL' },
  { postalCode: '8752', city: 'Glarus', cantonCode: 'GL' },
  { postalCode: '8753', city: 'Glarus', cantonCode: 'GL' },
  { postalCode: '8754', city: 'Glarus', cantonCode: 'GL' },
  { postalCode: '8755', city: 'Glarus', cantonCode: 'GL' },
  { postalCode: '2800', city: 'Delémont', cantonCode: 'JU' },
  { postalCode: '2801', city: 'Delémont', cantonCode: 'JU' },
  { postalCode: '2802', city: 'Delémont', cantonCode: 'JU' },
  { postalCode: '2803', city: 'Delémont', cantonCode: 'JU' },
  { postalCode: '2804', city: 'Delémont', cantonCode: 'JU' },
  { postalCode: '2805', city: 'Delémont', cantonCode: 'JU' }
];
